name: Deploy to REG.RU

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: salyut/package-lock.json
        
    - name: Install dependencies
      run: |
        cd salyut
        npm ci
        
    - name: Build project
      run: |
        cd salyut
        npm run build
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        YANDEX_MAPS_API_KEY: ${{ secrets.YANDEX_MAPS_API_KEY }}
        
    - name: Deploy to REG.RU via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: salyut/out/
        server-dir: ${{ secrets.FTP_SERVER_DIR }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.env*
          **/.env*/**
          **/README.md
          **/.github/**
          **/scripts/**
          **/docs/**
          **/*.md
          **/package.json
          **/package-lock.json
          **/next.config.js
          **/tailwind.config.ts
          **/tsconfig.json
          **/drizzle.config.ts
          **/postcss.config.js
          **/components.json
          **/.gitignore
          **/DOMAIN_CHANGE_INSTRUCTIONS.md
          **/IMPLEMENTATION_REPORT.md
          **/CITY_PAGES_README.md
          **/CHANGES.md
          **/SUMMARY.md
          **/PERFORMANCE_OPTIMIZATION.md
          **/HOSTING_CHECKLIST.md
          **/TELEGRAM_SETUP.md
          **/AUTO_DEPLOY_SETUP.md
          **/DEPLOY_INSTRUCTIONS.md
          **/DEPLOYMENT.md
          **/README.md
          **/lib/**
          **/hooks/**
          **/db/**
          **/supabase/**
          **/scripts/**
          **/docs/**
          **/.next/**
          **/node_modules/**
          **/public/_redirects
          **/public/.htaccess
          
    - name: Notify deployment success
      if: success()
      run: |
        echo "✅ Deployment to REG.RU completed successfully!"
        echo "🌐 Site should be available at: https://salutgrad.ru"
        
    - name: Notify deployment failure
      if: failure()
      run: |
        echo "❌ Deployment to REG.RU failed!"
        echo "Please check the logs above for details."
