name: Deploy to Reg.ru via FTP

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build && npm run export
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXT_PUBLIC_YANDEX_API_KEY: ${{ secrets.NEXT_PUBLIC_YANDEX_API_KEY }}
          SITE_VERSION: ${{ github.run_number }}-${{ github.sha }}
          BUILD_ID: build-${{ github.run_number }}-${{ github.sha }}
          
      - name: Deploy to REG.RU via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          local-dir: ./out/
          exclude: |
            **/.git*
            **/.git**
            **/.vscode*
            **/.next*
            **/node_modules/**
            .env
            .env.local
            .env.*.local
            .DS_Store
            *.pem
            npm-debug.log*
            yarn-debug.log*
            yarn-error.log*
            .vercel
            *.tsbuildinfo
            next-env.d.ts
            db/migrations/*_snapshot.json
            db/migrations/meta/[0-9]*_snapshot.json
            salyut/
            .github/
            scripts/
            docs/
            CI_CD_SETUP.md
            DOMAIN_CHANGE_INSTRUCTIONS.md
            ENV_VARIABLES_SETUP.md
            QUICK_START_CI_CD.md
            ENV_EXAMPLES.md
            README.md
            SUMMARY.md
            IMPLEMENTATION_REPORT.md
            CITY_PAGES_README.md
            CHANGES.md